name: lidar_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  injectable: ^2.4.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_cube: ^0.1.1
  # model_viewer_plus: ^1.7.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
