name: lidar_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  injectable: ^2.4.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_cube: ^0.1.1
  equatable: ^2.0.7
  # model_viewer_plus: ^1.7.0
  device_info_plus: ^10.1.0
  model_viewer_plus: ^1.9.3
  intl: ^0.20.2
  logging: ^1.2.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  ios: true
  image_path: "assets/app_icons/appstore.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/app_icons/
